spring.application.name=apigateway

server.port=8888

spring.main.web-application-type=reactive
eureka.client.service-url.DefaultZone=http://localhost:8761/eureka

#static routing

//spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:1111
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ADMISSION
spring.cloud.gateway.server.webflux.routes[0].id=admission
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/adm/**

//spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:2222
spring.cloud.gateway.server.webflux.routes[1].uri=lb://EXAM
spring.cloud.gateway.server.webflux.routes[1].id=exam
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/em/**
